version: '3'

services:
  bear-postgres:
    container_name: "bear-postgres"
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: bear
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#  bear-kafka:
#    container_name: "bear-kafka"
#    image: spotify/kafkaproxy
#    ports:
#      - "2181:2181"
#      - "9092:9092"
#    environment:
#      LISTENERS: "PLAINTEXT://0.0.0.0:9092"
#      ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
#      TOPICS: "test"
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    container_name: "kafka"
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#    depends_on:
#      - zookeeper
#    environment:
##      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
##      ALLOW_PLAINTEXT_LISTENER: 'yes'
##      LISTENERS: PLAINTEXT://0.0.0.0:9092
##      ADVERTISED_LISTENERS: PLAINTEXT://bear-kafka:9092
#
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_LISTENERS=SASL_PLAINTEXT://0.0.0.0:9092
#      - KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://kafka:9092
##      - KAFKA_ZOOKEEPER_USER=kafka
##      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
##      - KAFKA_INTER_BROKER_USER=interuser
##      - KAFKA_INTER_BROKER_PASSWORD=interpassword
##      - KAFKA_BROKER_USER=user
##      - KAFKA_BROKER_PASSWORD=password

#  docker run -p 2181:2181 -p 9092:9092 \
#  --env ADVERTISED_HOST=`boot2docker ip` \
#  --env ADVERTISED_PORT=9092 \
#  --env CONSUMER_THREADS=1 \
#  --env TOPICS=my-topic,some-other-topic \
#  --env ZK_CONNECT=kafka7zookeeper:2181/root/path \
#  --env GROUP_ID=mymirror \
#  spotify/kafkaproxy

